# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "customer-esn"
client_id = "PLACEHOLDER_CLIENT_ID"
application_url = "PLACEHOLDER_APPLICATION_URL"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "PLACEHOLDER_DEV_STORE_URL"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,write_customers"

[auth]
redirect_urls = [
  "PLACEHOLDER_REDIRECT_URL_1",
  "PLACEHOLDER_REDIRECT_URL_2",
  "PLACEHOLDER_REDIRECT_URL_3"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
